<%
	int i = 5/0;
%>

<div id='left'>
	<b>LEFT NAVIGATION CONTENT!!</b>
	<b>LEFT NAVIGATION CONTENT!!</b>
	<b>LEFT NAVIGATION CONTENT!!</b>
	<b>LEFT NAVIGATION CONTENT!!</b>
	<b>LEFT NAVIGATION CONTENT!!</b>
	<b>LEFT NAVIGATION CONTENT!!</b>
	<b>LEFT NAVIGATION CONTENT!!</b>
	<b>LEFT NAVIGATION CONTENT!!</b>
</div>